CREATE TABLE IF NOT EXISTS `news_posts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(190) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `excerpt` TEXT NULL,
  `body_html` MEDIUMTEXT NULL,
  `author` VARCHAR(190) NULL,
  `category` VARCHAR(64) NOT NULL DEFAULT 'general',
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `published_at` DATETIME NULL,
  `read_minutes` INT NULL,
  `cover_image` VARCHAR(255) NULL,
  `card_icon` VARCHAR(64) NULL,
  `card_gradient` VARCHAR(190) NULL,
  `link_url` VARCHAR(500) NULL,
  `link_label` VARCHAR(120) NULL,
  `deadline_label` VARCHAR(190) NULL,
  `tags` JSON NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `show_on_home` TINYINT(1) NOT NULL DEFAULT 0,
  `home_section` VARCHAR(32) NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_news_posts_slug` (`slug`),
  KEY `idx_news_status_pub` (`status`, `published_at`),
  KEY `idx_news_home` (`show_on_home`, `home_section`),
  KEY `idx_news_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(190) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `excerpt` TEXT NULL,
  `body_html` MEDIUMTEXT NULL,
  `author` VARCHAR(190) NULL,
  `category` VARCHAR(64) NOT NULL DEFAULT 'general',
  `status` VARCHAR(16) NOT NULL DEFAULT 'draft',
  `published_at` DATETIME NULL,
  `event_date` DATE NULL,
  `event_end_date` DATE NULL,
  `venue` VARCHAR(255) NULL,
  `read_minutes` INT NULL,
  `cover_image` VARCHAR(255) NULL,
  `card_icon` VARCHAR(64) NULL,
  `card_gradient` VARCHAR(190) NULL,
  `link_url` VARCHAR(500) NULL,
  `link_label` VARCHAR(120) NULL,
  `tags` JSON NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_events_slug` (`slug`),
  KEY `idx_events_status_date` (`status`, `event_date`),
  KEY `idx_events_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `homepage_slides` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `media_type` VARCHAR(16) NOT NULL DEFAULT 'image',
  `image_path` VARCHAR(255) NULL,
  `image_webp_path` VARCHAR(255) NULL,
  `poster_path` VARCHAR(255) NULL,
  `poster_webp_path` VARCHAR(255) NULL,
  `video_720_path` VARCHAR(255) NULL,
  `video_480_path` VARCHAR(255) NULL,
  `brand` VARCHAR(190) NULL,
  `title_html` VARCHAR(500) NULL,
  `body` TEXT NULL,
  `body_sub` TEXT NULL,
  `cta1_label` VARCHAR(120) NULL,
  `cta1_url` VARCHAR(255) NULL,
  `cta1_style` VARCHAR(32) NULL DEFAULT 'primary',
  `cta2_label` VARCHAR(120) NULL,
  `cta2_url` VARCHAR(255) NULL,
  `cta2_style` VARCHAR(32) NULL DEFAULT 'outline-white',
  `aria_label` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_slides_active_sort` (`is_active`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
