CREATE TABLE IF NOT EXISTS `faculty_profiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(190) NOT NULL,
  `aliases` JSON NULL,
  `name` VARCHAR(190) NOT NULL,
  `department` VARCHAR(190) NULL,
  `designation` VARCHAR(190) NULL,
  `hod` TINYINT(1) NOT NULL DEFAULT 0,
  `photo` VARCHAR(255) NULL,
  `qualifications` JSON NULL,
  `experience` JSON NULL,
  `skills` JSON NULL,
  `publications` JSON NULL,
  `research_preferences` JSON NULL,
  `publications_url` VARCHAR(500) NULL,
  `contact_phone` VARCHAR(64) NULL,
  `source` VARCHAR(64) NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`),
  KEY `idx_department` (`department`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
