CREATE TABLE IF NOT EXISTS `faculty_profile_submissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `submission_key` VARCHAR(64) NOT NULL,
  `submitted_at` DATETIME NOT NULL,
  `ip` VARCHAR(64) NULL,
  `college` VARCHAR(16) NOT NULL DEFAULT 'dms',
  `emp_name` VARCHAR(190) NOT NULL,
  `slug` VARCHAR(190) NOT NULL,
  `des_title` VARCHAR(190) NULL,
  `dep_name` VARCHAR(190) NULL,
  `research_preferences` JSON NULL,
  `publications_url` VARCHAR(500) NULL,
  `publications_file` VARCHAR(255) NULL,
  `publications` JSON NULL,
  `qualifications` JSON NULL,
  `skills` JSON NULL,
  `contact_phone` VARCHAR(64) NULL,
  `photo` VARCHAR(255) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_submission_key` (`submission_key`),
  KEY `idx_slug_status` (`slug`, `status`),
  KEY `idx_submitted_at` (`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
