<?php include('includes/header.php'); ?>
<div class="page-hero"><div class="page-hero-grid"></div><div class="container page-hero-content"><h1>Student Exchange &amp; Electives</h1><div class="breadcrumb-pmc"><a href="index.php">Home</a><span class="sep"><i class="bi bi-chevron-right"></i></span>Education &amp; Research <span class="sep"><i class="bi bi-chevron-right"></i></span><span class="current">Student Exchange &amp; Electives</span></div></div></div>
<section class="pmc-section"><div class="container"><div class="row g-5"><div class="col-lg-8"><div class="page-content fu">
<h2 class="sec-title" style="font-size:1.8rem;">Student Exchange &amp; Electives</h2>
<p>This page is currently under development and will be available soon. Please check back or <a href="contact.php" style="color:var(--teal);font-weight:700;">contact us</a> for more information.</p>
<div class="pmc-card text-center mt-4" style="border-radius:14px;">
  <div style="font-size:3rem;color:var(--teal);margin-bottom:16px;"><i class="bi bi-tools"></i></div>
  <h4>Coming Soon</h4>
  <p>We are working hard to bring you this content. In the meantime, visit us at the college or contact the relevant department.</p>
  <a href="contact.php" class="btn-pmc btn-pmc-primary mt-3"><i class="bi bi-envelope"></i> Contact Us</a>
</div></div></div><div class="col-lg-4 fu fu-delay-2"><div class="sidebar-widget"><div class="sw-head"><i class="bi bi-grid-fill"></i> Quick Navigation</div><div class="sw-body"><a class="sw-link" href="about.php"><i class="bi bi-building"></i>Introduction</a><a class="sw-link" href="vision-mission.php"><i class="bi bi-eye"></i>Vision &amp; Mission</a><a class="sw-link" href="faculty.php"><i class="bi bi-people"></i>Faculty</a><a class="sw-link" href="admissions.php"><i class="bi bi-mortarboard"></i>Admissions</a><a class="sw-link" href="vacant-seats.php"><i class="bi bi-door-open"></i>Vacant Seats</a><a class="sw-link" href="medical-education.php"><i class="bi bi-book"></i>Medical Education</a><a class="sw-link" href="curriculum.php"><i class="bi bi-journal-text"></i>Curriculum</a><a class="sw-link" href="examinations.php"><i class="bi bi-clipboard-pulse"></i>Examinations</a><a class="sw-link" href="umr.php"><i class="bi bi-flask"></i>UMR Research</a><a class="sw-link" href="contact.php"><i class="bi bi-envelope"></i>Contact Us</a></div></div><div class="sidebar-widget"><div class="sw-head"><i class="bi bi-hospital-fill"></i> Teaching Hospitals</div><div class="sw-body"><a class="sw-link" href="https://prime.edu.pk/pf/idx_kth.php" target="_blank"><i class="bi bi-hospital"></i>Kuwait Teaching Hospital</a><a class="sw-link" href="https://prime.edu.pk/pf/idx_mth.php" target="_blank"><i class="bi bi-heart-pulse"></i>Mercy Teaching Hospital</a><a class="sw-link" href="https://prime.edu.pk/pf/idx_pth.php" target="_blank"><i class="bi bi-capsule-pill"></i>Prime Teaching Hospital</a><a class="sw-link" href="https://prime.edu.pk/pf/community-development.php" target="_blank"><i class="bi bi-people-fill"></i>Community Dev. Center</a></div></div><div class="sidebar-widget"><div class="sw-head" style="background:var(--teal);"><i class="bi bi-mortarboard-fill"></i> Apply Now</div><div class="sw-body" style="padding:18px 20px;"><p style="font-family:var(--font-body);font-size:.84rem;color:var(--gray-mid);margin-bottom:14px;">Admissions for MBBS 2026-27 are open.</p><a href="admissions.php" class="btn-pmc btn-pmc-primary w-100 justify-content-center" style="font-size:.82rem;padding:11px;">Apply for MBBS 2026-27</a><a href="vacant-seats.php" class="btn-pmc btn-pmc-outline w-100 justify-content-center mt-2" style="font-size:.82rem;padding:11px;">Check Vacant Seats</a></div></div></div></div></div></section>
<section class="pmc-section-sm recog-strip"><div class="container"><div class="recog-grid"><div class="recog-cell"><div class="recog-ico"><i class="bi bi-patch-check-fill"></i></div><div class="recog-name">PM&DC</div></div><div class="recog-cell"><div class="recog-ico"><i class="bi bi-building-fill"></i></div><div class="recog-name">Riphah International University</div></div><div class="recog-cell"><div class="recog-ico"><i class="bi bi-award-fill"></i></div><div class="recog-name">CPSP</div></div><div class="recog-cell"><div class="recog-ico"><i class="bi bi-hospital-fill"></i></div><div class="recog-name">Ministry of Health</div></div><div class="recog-cell" style="border-right:none;"><div class="recog-ico"><i class="bi bi-globe-americas"></i></div><div class="recog-name">WHO</div></div></div></div></section>
<?php include('includes/footer.php'); ?>