<?php
return [
  '' => [
    'label' => 'Home',
    'section' => 'College',
    'title' => 'Best Medical College in Peshawar | PMC — MBBS',
    'description' => 'PMC Peshawar: a top private medical college in Peshawar and KP. PM&DC recognized MBBS, #1 private in KP (2024). Teaching hospitals, KMU admissions, Warsak Road.',
    'priority' => '1.0',
    'changefreq' => 'weekly',
  ],
  'pmc' => [
    'label' => 'Peshawar Medical College',
    'section' => 'College',
    'title' => 'PMC Peshawar | MBBS at a Private Medical College in KP',
    'description' => 'MBBS in Peshawar at PMC — a private medical college with PM&DC recognition, teaching hospitals, and first rank among private medical colleges of KP in 2024.',
    'priority' => '0.95',
    'changefreq' => 'monthly',
    'schema' => 'Course',
    'course_name' => 'MBBS',
  ],
  'about' => [
    'label' => 'About Us',
    'section' => 'College',
    'title' => 'About PMC | Medical College in Peshawar since 2005',
    'description' => 'About Peshawar Medical College: medical education in Peshawar since 2005, three teaching hospitals, PM&DC recognition, and Riphah International University affiliation.',
    'priority' => '0.8',
    'changefreq' => 'monthly',
  ],
  'admissions' => [
    'label' => 'Admissions',
    'section' => 'Academics',
    'title' => 'PMC Admission | MBBS & KMU Medical College Peshawar',
    'description' => 'PMC admission for MBBS via KMU and PM&DC. Merit, overseas, and foreign seats at a private medical college in Peshawar. Also FCPS/MCPS postgraduate pathways.',
    'priority' => '0.9',
    'changefreq' => 'weekly',
    'schema' => 'Course',
    'course_name' => 'MBBS',
  ],
  'vision-mission' => [
    'label' => 'Vision & Mission',
    'section' => 'College',
    'title' => 'Vision & Mission | Peshawar Medical College',
    'description' => 'Vision and mission of Peshawar Medical College: professional competence, ethical values, and medical education for KP and Pakistan.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'contact' => [
    'label' => 'Contact Us',
    'section' => 'College',
    'title' => 'Contact Peshawar Medical College | Warsak Road',
    'description' => 'Contact Peshawar Medical College on Warsak Road, Peshawar. Phone, email, and campus map for MBBS admissions and general enquiries.',
    'priority' => '0.7',
    'changefreq' => 'yearly',
  ],
  'departments' => [
    'label' => 'Departments',
    'section' => 'Academics',
    'title' => 'Medical Departments | Peshawar Medical College',
    'description' => 'Basic and clinical medical departments at Peshawar Medical College — anatomy to medicine, surgery, and specialties for MBBS training in Peshawar.',
    'priority' => '0.7',
    'changefreq' => 'monthly',
  ],
  'faculty' => [
    'label' => 'Faculty',
    'section' => 'College',
    'title' => 'Faculty | Best Medical Teachers in Peshawar — PMC',
    'description' => 'Meet PM&DC registered faculty at Peshawar Medical College, a leading medical college in Peshawar for MBBS and postgraduate teaching.',
    'priority' => '0.7',
    'changefreq' => 'monthly',
  ],
  'pg-medical-education' => [
    'label' => 'PG Medical Education',
    'section' => 'Academics',
    'title' => 'FCPS Training Peshawar | CPSP PG at PMC',
    'description' => 'FCPS and MCPS training in Peshawar at PMC — CPSP-recognised postgraduate medical education in teaching hospitals.',
    'priority' => '0.8',
    'changefreq' => 'monthly',
  ],
  'pg-surgery-residency' => [
    'label' => 'PG Surgery Residency',
    'section' => 'Academics',
    'title' => 'PG General Surgery Residency | PMC Peshawar',
    'description' => 'Postgraduate general surgery residency at Peshawar Medical College — structured surgical training in Peshawar teaching hospitals.',
    'priority' => '0.6',
    'changefreq' => 'yearly',
  ],
  'curriculum' => [
    'label' => 'Curriculum',
    'section' => 'Academics',
    'title' => 'MBBS Curriculum | Peshawar Medical College',
    'description' => 'MBBS curriculum at Peshawar Medical College: integrated basic sciences, clinical training, and PM&DC-aligned medical education in Peshawar.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'examinations' => [
    'label' => 'Examinations',
    'section' => 'Academics',
    'title' => 'Examinations | Peshawar Medical College',
    'description' => 'Examinations and assessments for MBBS and postgraduate students at Peshawar Medical College, Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'student-guide' => [
    'label' => 'Student Guide',
    'section' => 'Academics',
    'title' => 'Student Guide | Peshawar Medical College',
    'description' => 'Student guide for MBBS students at Peshawar Medical College — policies, facilities, and campus life in Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'faculty-research' => [
    'label' => 'Faculty Research',
    'section' => 'Academics',
    'title' => 'Faculty Research | Peshawar Medical College',
    'description' => 'Faculty research and publications at Peshawar Medical College, supporting medical research culture in Peshawar and KP.',
    'priority' => '0.5',
    'changefreq' => 'monthly',
  ],
  'clinical-skill-labs' => [
    'label' => 'Clinical Skill Labs',
    'section' => 'Academics',
    'title' => 'Clinical Skill Labs | PMC Peshawar',
    'description' => 'Clinical skill laboratories at Peshawar Medical College for hands-on MBBS training before hospital practice.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'e-health' => [
    'label' => 'E-Health',
    'section' => 'College',
    'title' => 'E-Health Service | Peshawar Medical College',
    'description' => 'Free e-health information service from Peshawar Medical College — public health guidance by phone for communities in KP.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'newsletter' => [
    'label' => 'Newsletter',
    'section' => 'News',
    'title' => 'Newsletter | Peshawar Medical College',
    'description' => 'Campus and college newsletters from the Department of Medical Sciences, Peshawar Medical College.',
    'priority' => '0.4',
    'changefreq' => 'monthly',
  ],
  'virtual-museum' => [
    'label' => 'Virtual Museum',
    'section' => 'Academics',
    'title' => 'Virtual Museum | Peshawar Medical College',
    'description' => 'Virtual museum collections from Peshawar Medical College for students and visitors.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'student-exchange' => [
    'label' => 'Student Exchange',
    'section' => 'Academics',
    'title' => 'Student Exchange | Peshawar Medical College',
    'description' => 'Student exchange and elective opportunities at Peshawar Medical College, Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'gallery' => [
    'label' => 'Gallery',
    'section' => 'News',
    'title' => 'Photo Gallery | Peshawar Medical College',
    'description' => 'Photos of campus life, labs, and events at Peshawar Medical College, Peshawar.',
    'priority' => '0.3',
    'changefreq' => 'monthly',
  ],
  'all-news' => [
    'label' => 'News',
    'section' => 'News',
    'title' => 'News | Peshawar Medical College',
    'description' => 'News and notices from Peshawar Medical College — admissions, rankings, and campus updates.',
    'priority' => '0.5',
    'changefreq' => 'weekly',
  ],
  'events' => [
    'label' => 'Events',
    'section' => 'News',
    'title' => 'Events | Peshawar Medical College',
    'description' => 'Events at Peshawar Medical College including academic conferences and student activities.',
    'priority' => '0.4',
    'changefreq' => 'weekly',
  ],
  'single-news' => [
    'label' => 'News Article',
    'section' => 'News',
    'title' => 'Campus News | Peshawar Medical College',
    'description' => 'News from Peshawar Medical College, a leading medical college in Peshawar.',
    'priority' => '0.2',
    'changefreq' => 'monthly',
    'og_type' => 'article',
  ],
  'event-single' => [
    'label' => 'Event',
    'section' => 'News',
    'title' => 'Event | Peshawar Medical College',
    'description' => 'Event details from Peshawar Medical College, Peshawar.',
    'priority' => '0.2',
    'changefreq' => 'monthly',
    'og_type' => 'article',
  ],
  'vacant-seats' => [
    'label' => 'Vacant Seats',
    'section' => 'Academics',
    'title' => 'MBBS Vacant Seats Peshawar | PMC Migration',
    'description' => 'Vacant MBBS seats and migration at PMC Peshawar, a private medical college on Warsak Road.',
    'priority' => '0.5',
    'changefreq' => 'monthly',
  ],
  'portal' => [
    'label' => 'Portal',
    'section' => 'College',
    'title' => 'Student Portal | Peshawar Medical College',
    'description' => 'Student and faculty portal links for Peshawar Medical College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'portal-login' => [
    'label' => 'Portal Login',
    'section' => 'College',
    'title' => 'Portal Login | Peshawar Medical College',
    'description' => 'Portal login for Peshawar Medical College students and staff.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'umr' => [
    'label' => 'UMR',
    'section' => 'College',
    'title' => 'UMR Society | Peshawar Medical College',
    'description' => 'Undergraduate Medical Research Society at Peshawar Medical College.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'student-research' => [
    'label' => 'Student Research',
    'section' => 'Academics',
    'title' => 'Student Research | Peshawar Medical College',
    'description' => 'Student research opportunities at Peshawar Medical College, Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'faculty-all' => [
    'label' => 'All Faculty',
    'section' => 'College',
    'title' => 'All Faculty | Peshawar Medical College',
    'description' => 'Full faculty directory of Peshawar Medical College.',
    'priority' => '0.4',
    'changefreq' => 'monthly',
  ],
  'literary-society' => [
    'label' => 'Literary Society',
    'section' => 'College',
    'title' => 'Literary Society | Peshawar Medical College',
    'description' => 'Society for literature and arts at Peshawar Medical College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'sports-society' => [
    'label' => 'Sports Society',
    'section' => 'College',
    'title' => 'Sports Society | Peshawar Medical College',
    'description' => 'Sports and athletics at Peshawar Medical College, Peshawar.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'social-welfare' => [
    'label' => 'Social Welfare',
    'section' => 'College',
    'title' => 'Social Welfare Society | Peshawar Medical College',
    'description' => 'Social Welfare Society at Peshawar Medical College — community service in Peshawar.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'education-literature' => [
    'label' => 'Educational Literature',
    'section' => 'Academics',
    'title' => 'Educational Literature | Peshawar Medical College',
    'description' => 'Educational literature from Peshawar Medical College faculty and students.',
    'priority' => '0.4',
    'changefreq' => 'monthly',
  ],
  'sitemap-page' => [
    'label' => 'Sitemap',
    'section' => 'College',
    'title' => 'Sitemap | Peshawar Medical College',
    'description' => 'HTML sitemap of Peshawar Medical College and the Department of Medical Sciences.',
    'priority' => '0.3',
    'changefreq' => 'monthly',
  ],
];
